name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.8
        with:
          heroku_api_key: ${{secrets.HEROKU_KEY}}
          heroku_app_name: "samhiggs-portfolio-dev" #Must be unique in Heroku
          heroku_email: "samhiggs@pm.me"