name: Python Pull Request Workflow

on: [pull_request]
jobs:
  qa:
    name: Linting
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python
        with:
          python-version: 3.8
      - name: Run Styleguide Check
        uses: wemake-services/wemake-python-styleguide@0.14.1
        continue-on-error: true
        with:
          reporter: 'github-pr-review'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}